# Uncomment the next line to define a global platform for your project
platform :ios, '10.1'

target 'myVacay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myVacay
  # pod 'AFNetworking'
  pod 'AFNetworking', '~> 2.5'
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'BDBOAuth1Manager'
  pod 'ROGoogleTranslate'

end
